### ISSUE TITLE
Can't enter Nova Tera server while using this toolbox

### ISSUE THREAD

**Issue by mateustaio** [tera-classic-toolbox/tera-toolbox-nova#1]
Hello, i don't know if i'm doing something wrong or if this toolbox stopped working for Nova Tera but i get stuck on the server list, the server list shows the two servers (normal and toolbox) but when i click enter nothing happens, if you can please help me, thank you very much.

**Comment by justkeepquiet** [comment]
Hi. There is currently no way to make the toolbox work on Nova. Toolbox will only work if the Nova administration allows its use.
